%Check the mat file generated by flirt registration
%Questions and comments chen.yasheng@gmail.com

function sign_rerun = check_flirt_mat_rerun(name_mat)

   sign_rerun=0;

   mat_out = load_flirt_mat(name_mat);
   mat_out = mat_out(1:3,1:3);
   mat_det = abs(1-det(mat_out));
   mat1 = abs(1-mat_out(1,1));
   mat2 = abs(1-mat_out(2,2));
   mat3 = abs(1-mat_out(3,3));

   if mat1>0.2 | mat2>0.2 | mat3>0.2 | mat_det>0.2 
      sign_rerun=1;
   end;

   clear mat_out mat_det mat1 mat2 mat3;


